resolver: nightly-2016-09-07

packages:
- 'has-sci-physics'
- 'has-sci-physics-examples'

extra-deps:
  - gloss-1.10.2.5
  - gloss-raster-1.10.2.4
  - algebra-4.3
  - eigen-2.1.6
  
flags: {}

extra-package-dbs: []